### PR TITLE
Correct fix for Python 3.9

### PR DESCRIPTION
**Pull request by YoYoost**
As mentioned in https://github.com/maximeh/script.myepisodes/pull/18#issuecomment-1191022412 I made a mistake while changing and testing. The original python issue I linked to even mentions CamelCase.

### CODE REVIEW

**Comment by maximeh** [comment]
How did you test in the first place then? To be fair; I didn't and that's my fault.

I wonder if there's any way of having some CI test in place to check theses; I would really like to automate all that stuff; I barely use Kodi theses days myself so it's even more effort to maintain this.

I'll merge + release later today I think.

**Comment by mkatsevVR** [comment]
> I wonder if there's any way of having some CI test in place to check theses

Typechecker could've caught this particular issue, although I'd expect most potential bugs to be related to using external APIs (Kodi and myepisodes) which would require an integration test and likely rather challenging to setup.

**Comment by maximeh** [comment]
That's a good point, and already a good start. I'll look into that, python
is not my day to day anymore since a few years; I've lost touch a little
bit.
Any pointer?

Best,
 - Max

**Comment by mkatsevVR** [comment]
For typecheck, something like https://github.com/jpetrucciani/mypy-check. 

For mocks, magicmock probably?

**Comment by mkatsevVR** [comment]
@maximeh  do you need to do anything to publish the update to kodi? https://kodi.tv/addons/matrix/script.myepisodes still shows 3.0.1 as the latest version

**Comment by maximeh** [comment]
I replied via email but Github doesn't seem to pick it up.
------
Thanks for pinging me; I forgot to check that it was done.

I have pinged on the PR to merge the update to Kodi:
https://github.com/xbmc/repo-scripts/pull/2309

Feel free to add your voice too there :)

**Comment by maximeh** [comment]
It got approved and merged \o/

I'm still working on the testing part and some refactor too.

**Comment by maximeh** [comment]
Thanks for pinging me; I forgot to check that it was done.

I have pinged on the PR to merge the update to Kodi:
https://github.com/xbmc/repo-scripts/pull/2309

Feel free to add your voice too there :)

Best,
 - Max

**Pull request merged**
